library;

/// Local crest catalog for the monthly competitions supplied with the app.
class MonthlyCompetitionLogoGroup {
  const MonthlyCompetitionLogoGroup({
    required this.name,
    required this.season,
    required this.slugs,
  });

  final String name;
  final String season;
  final List<String> slugs;
}

const List<MonthlyCompetitionLogoGroup> kMonthlyCompetitionLogoGroups =
    <MonthlyCompetitionLogoGroup>[
      MonthlyCompetitionLogoGroup(
        name: 'الدوري الإنجليزي الممتاز',
        season: '2026-27',
        slugs: <String>[
          'arsenal',
          'aston-villa',
          'bournemouth',
          'brentford',
          'brighton',
          'chelsea',
          'coventry-city',
          'crystal-palace',
          'everton',
          'fulham',
          'hull-city',
          'ipswich',
          'leeds-united',
          'liverpool',
          'manchester-city',
          'manchester-united',
          'newcastle',
          'nottingham-forest',
          'sunderland',
          'tottenham',
        ],
      ),
      MonthlyCompetitionLogoGroup(
        name: 'الدوري الألماني',
        season: '2026-27',
        slugs: <String>[
          'augsburg',
          'bayer-leverkusen',
          'bayern-munchen',
          'borussia-dortmund',
          'borussia-monchengladbach',
          'eintracht-frankfurt',
          'freiburg',
          'hamburger-sv',
          'hoffenheim',
          'koln',
          'mainz-05',
          'paderborn',
          'rb-leipzig',
          'schalke-04',
          'sv-elversberg',
          'union-berlin',
          'vfb-stuttgart',
          'werder-bremen',
        ],
      ),
      MonthlyCompetitionLogoGroup(
        name: 'الدوري الإسباني',
        season: '2026-27',
        slugs: <String>[
          'athletic-club',
          'atletico-madrid',
          'barcelona',
          'celta',
          'deportivo',
          'deportivo-la-coruna',
          'elche',
          'espanyol',
          'getafe',
          'levante',
          'malaga',
          'osasuna',
          'racing',
          'rayo-vallecano',
          'real-betis',
          'real-madrid',
          'real-sociedad',
          'sevilla',
          'valencia',
          'villarreal',
        ],
      ),
      MonthlyCompetitionLogoGroup(
        name: 'دوري أبطال أوروبا',
        season: '2025-26',
        slugs: <String>[
          'paris-saint-germain',
          'bayern-munchen',
          'real-madrid',
          'liverpool',
          'inter',
          'manchester-city',
          'arsenal',
          'barcelona',
          'atletico-madrid',
          'borussia-dortmund',
          'roma',
          'sporting-cp',
          'aston-villa',
          'fc-porto',
          'manchester-united',
          'club-brugge',
          'real-betis',
          'psv',
          'feyenoord',
          'lille',
          'bodo-glimt',
          'napoli',
          'rb-leipzig',
          'villarreal',
          'fenerbahce',
          'shakhtar',
          'galatasaray',
          'slavia-praha',
          's-bratislava',
          'vfb-stuttgart',
          'aek-athens',
          'lask',
          'como-1907',
          'rc-lens',
          'viking',
          'sabah',
        ],
      ),
      MonthlyCompetitionLogoGroup(
        name: 'الدوري الأوروبي',
        season: '2025-26',
        slugs: <String>[
          'milan',
          'juventus',
          'bayer-leverkusen',
          'hoffenheim',
          'real-sociedad',
          'celta',
          'marseille',
          'rennes',
          'bournemouth',
          'sunderland',
          'crystal-palace',
          'az-alkmaar',
          'torreense',
          'union-saint-gilloise',
          'sparta-praha',
          'olympiacos',
          'sturm-graz',
          'celtic',
          'hapoel-beer-sheva',
          'nec-nijmegen',
          'levski',
          'dinamo-zagreb',
          'celje',
          'lyon',
          'ararat-armenia',
          'jagiellonia',
          'omonoia',
          'viktoria-plzen',
          'lillestrom',
          'salzburg',
          'besiktas',
          'lech-poznan',
          'benfica',
          'ofi',
          'ferencvaros',
          'anderlecht',
        ],
      ),
    ];

/// أسماء الفرق كما تخزّنها `football_data.teams` (بالعربية) مقابل شريحة
/// الشعار المرفق في `assets/team_logos/`. البحث يجري أولًا بالنص كما ورد
/// ثم بصيغة مُطبَّعة عبر [_normalizeArabic]، فتُطابق فروق الهمزة والتاء
/// المربوطة والألف المقصورة دون سطر لكل صيغة.
///
/// كل قيمة هنا موجودة في [_monthlyLogoSlugs] وفي مجلد الأصول. الفرق التي
/// لا شعار مرفق لها (أغلب الدوري الإيطالي والسعودي) عمدًا خارج الخريطة:
/// تبقى على دائرة الحروف حتى تُضاف ملفاتها.
final Map<String, String> _arabicTeamLogoAliases = <String, String>{
  // CAF national teams / AFCON 2027 qualifiers
  'الجزائر': 'algeria',
  'أنغولا': 'angola',
  'بنين': 'benin',
  'بوتسوانا': 'botswana',
  'بوركينا فاسو': 'burkina-faso',
  'بوروندي': 'burundi',
  'الكاميرون': 'cameroon',
  'الرأس الأخضر': 'cape-verde',
  'أفريقيا الوسطى': 'central-african-republic',
  'تشاد': 'chad',
  'جزر القمر': 'comoros',
  'الكونغو': 'congo',
  'الكونغو الديمقراطية': 'democratic-republic-of-congo',
  'جيبوتي': 'djibouti',
  'مصر': 'egypt',
  'غينيا الاستوائية': 'equatorial-guinea',
  'إريتريا': 'eritrea',
  'إسواتيني': 'eswatini',
  'إثيوبيا': 'ethiopia',
  'الغابون': 'gabon',
  'غامبيا': 'gambia',
  'غانا': 'ghana',
  'غينيا': 'guinea',
  'غينيا بيساو': 'guinea-bissau',
  'ساحل العاج': 'ivory-coast',
  'كينيا': 'kenya',
  'ليسوتو': 'lesotho',
  'ليبيريا': 'liberia',
  'ليبيا': 'libya',
  'مدغشقر': 'madagascar',
  'مالاوي': 'malawi',
  'مالي': 'mali',
  'موريتانيا': 'mauritania',
  'موريشيوس': 'mauritius',
  'المغرب': 'morocco',
  'موزمبيق': 'mozambique',
  'ناميبيا': 'namibia',
  'النيجر': 'niger',
  'نيجيريا': 'nigeria',
  'رواندا': 'rwanda',
  'ساو تومي وبرينسيبي': 'sao-tome-and-principe',
  'السنغال': 'senegal',
  'سيشل': 'seychelles',
  'سيراليون': 'sierra-leone',
  'الصومال': 'somalia',
  'جنوب أفريقيا': 'south-africa',
  'جنوب السودان': 'south-sudan',
  'السودان': 'sudan',
  'تنزانيا': 'tanzania',
  'توغو': 'togo',
  'تونس': 'tunisia',
  'أوغندا': 'uganda',
  'زامبيا': 'zambia',
  'زيمبابوي': 'zimbabwe',
  // الدوري الإنجليزي
  'أرسنال': 'arsenal',
  'الأهلي المصري': 'al-ahly',
  'العين': 'al-ain',
  'أوكلاند سيتي': 'auckland-city-fc',
  'بوكا جونيورز': 'boca-juniors',
  'بوتافوغو': 'botafogo',
  'الترجي الرياضي التونسي': 'esperance',
  'فلامنغو': 'flamengo',
  'فلومينينسي': 'fluminense',
  'إنتر ميامي': 'inter-miami-cf',
  'لوس أنجلوس إف سي': 'los-angeles-fc',
  'ماميلودي صن داونز': 'mamelodi-sundowns',
  'مونتيري': 'monterrey',
  'باتشوكا': 'pachuca',
  'بالميراس': 'palmeiras',
  'ريفر بليت': 'river-plate',
  'سياتل ساوندرز': 'seattle-sounders-fc',
  'أولسان HD': 'ulsan-hd-fc',
  'أوراوا ريد دايموندز': 'urawa-reds',
  'الوداد': 'wydad-ac',
  'أستون فيلا': 'aston-villa',
  'برايتون': 'brighton',
  'بورنموث': 'bournemouth',
  'برينتفورد': 'brentford',
  'تشيلسي': 'chelsea',
  'كوفنتري سيتي': 'coventry-city',
  'كريستال بالاس': 'crystal-palace',
  'إيفرتون': 'everton',
  'فولهام': 'fulham',
  'هال سيتي': 'hull-city',
  'إبسويتش تاون': 'ipswich',
  'إبسويتش': 'ipswich',
  'ليدز يونايتد': 'leeds-united',
  'ليدز': 'leeds-united',
  'ليفربول': 'liverpool',
  'مانشستر سيتي': 'manchester-city',
  'مانشستر يونايتد': 'manchester-united',
  'نيوكاسل': 'newcastle',
  'نيوكاسل يونايتد': 'newcastle',
  'نوتينغهام فورست': 'nottingham-forest',
  'نوتنغهام فورست': 'nottingham-forest',
  'سندرلاند': 'sunderland',
  'توتنهام': 'tottenham',
  // الدوري الألماني
  'بايرن ميونخ': 'bayern-munchen',
  'باير ليفركوزن': 'bayer-leverkusen',
  'بوروسيا دورتموند': 'borussia-dortmund',
  'بوروسيا مونشنغلادباخ': 'borussia-monchengladbach',
  'أوغسبورغ': 'augsburg',
  'يونيون برلين': 'union-berlin',
  'هامبورغ': 'hamburger-sv',
  'كولن': 'koln',
  'كولون': 'koln',
  'ماينز': 'mainz-05',
  'لايبزيغ': 'rb-leipzig',
  'شالكه': 'schalke-04',
  'فرايبورغ': 'freiburg',
  'بادربورن': 'paderborn',
  'آينتراخت فرانكفورت': 'eintracht-frankfurt',
  'إينتراخت فرانكفورت': 'eintracht-frankfurt',
  'إلفرسبيرغ': 'sv-elversberg',
  'فيردر بريمن': 'werder-bremen',
  'هوفنهايم': 'hoffenheim',
  'شتوتغارت': 'vfb-stuttgart',
  // الدوري الإسباني
  'ريال مدريد': 'real-madrid',
  'برشلونة': 'barcelona',
  'أتلتيكو مدريد': 'atletico-madrid',
  'أتلتيك بلباو': 'athletic-club',
  'ريال بيتيس': 'real-betis',
  'ريال سوسيداد': 'real-sociedad',
  'سيلتا فيغو': 'celta',
  'سيلتا': 'celta',
  'ديبورتيفو لاكورونيا': 'deportivo-la-coruna',
  'ديبورتيفو': 'deportivo',
  'إلتشي': 'elche',
  'إسبانيول': 'espanyol',
  'اسبانيول': 'espanyol',
  'خيتافي': 'getafe',
  'ليفانتي': 'levante',
  'ملقا': 'malaga',
  'مالاغا': 'malaga',
  'أوساسونا': 'osasuna',
  'راسينغ سانتاندير': 'racing',
  'رايو فايكانو': 'rayo-vallecano',
  'إشبيلية': 'sevilla',
  'فالنسيا': 'valencia',
  'فياريال': 'villarreal',
  // الدوري الإيطالي (المتوفّر شعارها فقط)
  'ميلان': 'milan',
  'إيه سي ميلان': 'milan',
  'يوفنتوس': 'juventus',
  'إنتر ميلان': 'inter',
  'إنتر': 'inter',
  'روما': 'roma',
  'نابولي': 'napoli',
  'كومو': 'como-1907',
  // الدوري الفرنسي
  'باريس سان جيرمان': 'paris-saint-germain',
  'مارسيليا': 'marseille',
  'مرسيليا': 'marseille',
  'ليون': 'lyon',
  'ليل': 'lille',
  'رين': 'rennes',
  'لانس': 'rc-lens',
  // الدوري السعودي (المتوفّر شعارها فقط)
  'الاتحاد': 'al-ittihad',
  'النصر': 'al-nassr',
  // دوري أبطال أوروبا والدوري الأوروبي
  'أيك أثينا': 'aek-athens',
  'أندرلخت': 'anderlecht',
  'أرارات أرمينيا': 'ararat-armenia',
  'ألكمار': 'az-alkmaar',
  'بنفيكا': 'benfica',
  'بشيكتاش': 'besiktas',
  'بشتکاش': 'besiktas',
  'بودو/غليمت': 'bodo-glimt',
  'بودو غليمت': 'bodo-glimt',
  'تسيليه': 'celje',
  'سلتيك': 'celtic',
  'كلوب بروج': 'club-brugge',
  'دينامو زغرب': 'dinamo-zagreb',
  'فنربخشة': 'fenerbahce',
  'فرنكفاروش': 'ferencvaros',
  'فيرينكفاروس': 'ferencvaros',
  'فينورد': 'feyenoord',
  'فاینورد': 'feyenoord',
  'غلطة سراي': 'galatasaray',
  'هابوعيل بئر السبع': 'hapoel-beer-sheva',
  'ياجيلونيا بياليستوك': 'jagiellonia',
  'لاسك لينز': 'lask',
  'ليخ بوزنان': 'lech-poznan',
  'ليفسكي صوفيا': 'levski',
  'ليليستروم': 'lillestrom',
  'نايميخن': 'nec-nijmegen',
  'نیمیجن': 'nec-nijmegen',
  'أوفي كريت': 'ofi',
  'أولمبياكوس': 'olympiacos',
  'أومونيا نيقوسيا': 'omonoia',
  'أمونيا نيقوسيا': 'omonoia',
  'بورتو': 'fc-porto',
  'أيندهوفن': 'psv',
  'سابا': 'sabah',
  'سالزبورغ': 'salzburg',
  'شاختار دونيتسك': 'shakhtar',
  'سلافيا براغ': 'slavia-praha',
  'سلوفان براتيسلافا': 's-bratislava',
  'سبارتا براغ': 'sparta-praha',
  'سبورتينغ لشبونة': 'sporting-cp',
  'شتورم غراتس': 'sturm-graz',
  'توريينسي': 'torreense',
  'يونيون سان جيلواز': 'union-saint-gilloise',
  'فيكتوريا بلزن': 'viktoria-plzen',
  'فايكينغ': 'viking',
  'فايكينج': 'viking',
  'الهلال': 'al-hilal',
  'الفيصلي': 'al-faisaly',
  'أبها': 'abha',
  'الأهلي': 'al-ahli',
  'الاتفاق': 'al-ettifaq',
  'الفتح': 'al-fateh',
  'الفيحاء': 'al-fayha',
  'الحزم': 'al-hazem',
  'الخليج': 'al-khaleej',
  'الخلود': 'al-kholood',
  'القادسية': 'al-qadsiah',
  'الرياض': 'al-riyadh',
  'الشباب': 'al-shabab',
  'التعاون': 'al-taawoun',
  'ديبورتيفو ألافيس': 'alaves',
  'أتالانتا': 'atalanta',
  'بولونيا': 'bologna',
  'كالياري': 'cagliari',
  'الدرعية': 'diriyah',
  'فيورنتينا': 'fiorentina',
  'فروزينوني': 'frosinone',
  'جنوى': 'genoa',
  'لاتسيو': 'lazio',
  'ليتشي': 'lecce',
  'مونزا': 'monza',
  'نيوم': 'neom',
  'بارما': 'parma',
  'ساسولو': 'sassuolo',
  'تورينو': 'torino',
  'أودينيزي': 'udinese',
  'فينيسيا': 'venezia',
  // منتخبات أوروبا (دوري الأمم الأوروبية)
  'ألبانيا': 'albania',
  'أندورا': 'andorra',
  'أرمينيا': 'armenia',
  'النمسا': 'austria',
  'أذربيجان': 'azerbaijan',
  'بيلاروسيا': 'belarus',
  'بلجيكا': 'belgium',
  'البوسنة والهرسك': 'bosnia-herzegovina',
  'بلغاريا': 'bulgaria',
  'كرواتيا': 'croatia',
  'قبرص': 'cyprus',
  'التشيك': 'czech-republic',
  'الدنمارك': 'denmark',
  'هولندا': 'netherlands',
  'إنجلترا': 'england',
  'إستونيا': 'estonia',
  'جزر فارو': 'faroe-islands',
  'فنلندا': 'finland',
  'فرنسا': 'france',
  'جورجيا': 'georgia',
  'ألمانيا': 'germany',
  'جبل طارق': 'gibraltar',
  'اليونان': 'greece',
  'المجر': 'hungary',
  'آيسلندا': 'iceland',
  'إسرائيل': 'israel',
  'إيطاليا': 'italy',
  'كازاخستان': 'kazakhstan',
  'كوسوفو': 'kosovo',
  'لاتفيا': 'latvia',
  'ليختنشتاين': 'liechtenstein',
  'ليتوانيا': 'lithuania',
  'لوكسمبورغ': 'luxembourg',
  'مالطا': 'malta',
  'مولدوفا': 'moldova',
  'الجبل الأسود': 'montenegro',
  'مقدونيا الشمالية': 'north-macedonia',
  'أيرلندا الشمالية': 'northern-ireland',
  'النرويج': 'norway',
  'بولندا': 'poland',
  'البرتغال': 'portugal',
  'جمهورية أيرلندا': 'ireland',
  'رومانيا': 'romania',
  'سان مارينو': 'san-marino',
  'إسكتلندا': 'scotland',
  'صربيا': 'serbia',
  'سلوفاكيا': 'slovakia',
  'سلوفينيا': 'slovenia',
  'إسبانيا': 'spain',
  'السويد': 'sweden',
  'سويسرا': 'switzerland',
  'تركيا': 'turkey',
  'أوكرانيا': 'ukraine',
  'ويلز': 'wales',
  // منتخبات الخليج (كأس الخليج)
  'البحرين': 'bahrain',
  'قطر': 'qatar',
  'اليمن': 'yemen',
  'الإمارات': 'united-arab-emirates',
  'السعودية': 'saudi-arabia',
  'سلطنة عمان': 'oman',
  'العراق': 'iraq',
  'الكويت': 'kuwait',
  // أندية الدوري الفرنسي بلا شعار سابق
  'أنجيه': 'angers',
  'موناكو': 'monaco',
  'أوكسير': 'auxerre',
  'بريست': 'brest',
  'لوهافر': 'le-havre',
  'لومان': 'le-mans',
  'لوريان': 'lorient',
  'نيس': 'nice',
  'باريس إف سي': 'paris-fc',
  'ستراسبورغ': 'strasbourg',
  'تولوز': 'toulouse',
  'تروا': 'troyes',
};

/// نسخة مُطبَّعة من [_arabicTeamLogoAliases] تُبنى مرّة واحدة.
final Map<String, String> _normalizedArabicTeamLogoAliases = <String, String>{
  for (final MapEntry<String, String> e in _arabicTeamLogoAliases.entries)
    _normalizeArabic(e.key): e.value,
};

/// يوحّد صور الحروف التي تختلف بين مصادر الأسماء: التطويل والتشكيل
/// يُحذفان، وهمزات الألف تُردّ إلى ألف، والتاء المربوطة إلى هاء، والألف
/// المقصورة إلى ياء، والمسافات المتكرّرة إلى واحدة.
String _normalizeArabic(String value) => value
    .replaceAll(RegExp('[\u0640\u064B-\u0652]'), '')
    .replaceAll(RegExp('[\u0622\u0623\u0625\u0671]'), '\u0627')
    .replaceAll('\u0629', '\u0647')
    .replaceAll('\u0649', '\u064A')
    .replaceAll('\u0624', '\u0648')
    .replaceAll('\u0626', '\u064A')
    .replaceAll(RegExp(r'\s+'), ' ')
    .trim();

const Map<String, String> _clubWorldCupEnglishAliases = <String, String>{
  'psg': 'paris-saint-germain',
  'al-ain-fc': 'al-ain',
  'inter-miami': 'inter-miami-cf',
  'inter-miami-fc': 'inter-miami-cf',
  'rb-salzburg': 'salzburg',
  'red-bull-salzburg': 'salzburg',
  'esp-rance': 'esperance',
  'esp-rance-tunis': 'esperance',
  'esp-rance-de-tunis': 'esperance',
  'esperance-tunis': 'esperance',
  'esperance-de-tunis': 'esperance',
  'es-tunis': 'esperance',
  'urawa-red-diamonds': 'urawa-reds',
  'atl-tico-atlanta': 'atletico-atlanta',
};

String? teamLogoAssetPath(String? teamName) {
  if (teamName == null || teamName.trim().isEmpty) return null;
  final String trimmed = teamName.trim();
  final String? aliased =
      _arabicTeamLogoAliases[trimmed] ??
      _normalizedArabicTeamLogoAliases[_normalizeArabic(trimmed)];
  final String slugified = _slugifyTeamName(trimmed);
  final String slug =
      aliased ?? _clubWorldCupEnglishAliases[slugified] ?? slugified;
  if (slug.isEmpty || !_monthlyLogoSlugs.contains(slug)) return null;
  return 'assets/team_logos/$slug.png';
}

String teamLogoLabel(String slug) => slug
    .split('-')
    .map(
      (word) => word.isEmpty ? word : word[0].toUpperCase() + word.substring(1),
    )
    .join(' ');

String _slugifyTeamName(String name) {
  final String normalized = name
      .toLowerCase()
      .replaceAll(RegExp("['’`]"), '')
      .replaceAll(RegExp(r'\s+'), '-')
      .replaceAll(RegExp(r'[^a-z0-9-]+'), '-');
  final String slug = normalized
      .replaceAll(RegExp(r'-+'), '-')
      .replaceAll(RegExp(r'^-+|-+$'), '');
  const Map<String, String> aliases = <String, String>{
    'ipswich-town': 'ipswich',
    'newcastle-united': 'newcastle',
    'tottenham-hotspur': 'tottenham',
    'bayern-munich': 'bayern-munchen',
    'porto': 'fc-porto',
    'slovan-bratislava': 's-bratislava',
    'bratislava': 's-bratislava',
    'psv-eindhoven': 'psv',
    'sporting-lisbon': 'sporting-cp',
    'inter-milan': 'inter',
  };
  return aliases[slug] ?? slug;
}

const Set<String> _monthlyLogoSlugs = <String>{
  // CAF national-team flag assets
  'algeria',
  'angola',
  'benin',
  'botswana',
  'burkina-faso',
  'burundi',
  'cameroon',
  'cape-verde',
  'central-african-republic',
  'chad',
  'comoros',
  'congo',
  'democratic-republic-of-congo',
  'djibouti',
  'egypt',
  'equatorial-guinea',
  'eritrea',
  'eswatini',
  'ethiopia',
  'gabon',
  'gambia',
  'ghana',
  'guinea',
  'guinea-bissau',
  'ivory-coast',
  'kenya',
  'lesotho',
  'liberia',
  'libya',
  'madagascar',
  'malawi',
  'mali',
  'mauritania',
  'mauritius',
  'morocco',
  'mozambique',
  'namibia',
  'niger',
  'nigeria',
  'rwanda',
  'sao-tome-and-principe',
  'senegal',
  'seychelles',
  'sierra-leone',
  'somalia',
  'south-africa',
  'south-sudan',
  'sudan',
  'tanzania',
  'togo',
  'tunisia',
  'uganda',
  'zambia',
  'zimbabwe',
  'auckland-fc',
  'al-ain',
  'mamelodi-sundowns',
  'seattle-sounders-fc',
  'inter-miami-cf',
  'esperance',
  'pachuca',
  'palmeiras',
  'wydad-ac',
  'boca-juniors',
  'urawa-reds',
  'los-angeles-fc',
  'botafogo',
  'ulsan-hd-fc',
  'fluminense',
  'flamengo',
  'auckland-city-fc',
  'monterrey',
  'river-plate',
  'atletico-atlanta',
  'al-ittihad',
  'al-nassr',
  'arsenal',
  'aston-villa',
  'bournemouth',
  'brentford',
  'brighton',
  'chelsea',
  'coventry-city',
  'crystal-palace',
  'everton',
  'fulham',
  'hull-city',
  'ipswich',
  'leeds-united',
  'liverpool',
  'manchester-city',
  'manchester-united',
  'newcastle',
  'nottingham-forest',
  'sunderland',
  'tottenham',
  'augsburg',
  'bayer-leverkusen',
  'bayern-munchen',
  'borussia-dortmund',
  'borussia-monchengladbach',
  'eintracht-frankfurt',
  'freiburg',
  'hamburger-sv',
  'hoffenheim',
  'koln',
  'mainz-05',
  'paderborn',
  'rb-leipzig',
  'schalke-04',
  'sv-elversberg',
  'union-berlin',
  'vfb-stuttgart',
  'werder-bremen',
  'athletic-club',
  'atletico-madrid',
  'barcelona',
  'celta',
  'deportivo',
  'deportivo-la-coruna',
  'elche',
  'espanyol',
  'getafe',
  'levante',
  'malaga',
  'osasuna',
  'racing',
  'rayo-vallecano',
  'real-betis',
  'real-madrid',
  'real-sociedad',
  'sevilla',
  'valencia',
  'villarreal',
  'paris-saint-germain',
  'inter',
  'roma',
  'sporting-cp',
  'fc-porto',
  'club-brugge',
  'psv',
  'feyenoord',
  'lille',
  'bodo-glimt',
  'napoli',
  'fenerbahce',
  'shakhtar',
  'galatasaray',
  'slavia-praha',
  's-bratislava',
  'aek-athens',
  'lask',
  'como-1907',
  'rc-lens',
  'viking',
  'sabah',
  'milan',
  'juventus',
  'marseille',
  'rennes',
  'az-alkmaar',
  'torreense',
  'union-saint-gilloise',
  'sparta-praha',
  'olympiacos',
  'sturm-graz',
  'celtic',
  'hapoel-beer-sheva',
  'nec-nijmegen',
  'levski',
  'dinamo-zagreb',
  'celje',
  'lyon',
  'ararat-armenia',
  'jagiellonia',
  'omonoia',
  'viktoria-plzen',
  'lillestrom',
  'salzburg',
  'besiktas',
  'lech-poznan',
  'benfica',
  'ofi',
  'ferencvaros',
  'anderlecht',
  'al-hilal',
  'al-faisaly',
  'abha',
  'al-ahli',
  'al-ettifaq',
  'al-fateh',
  'al-fayha',
  'al-hazem',
  'al-khaleej',
  'al-kholood',
  'al-qadsiah',
  'al-riyadh',
  'al-shabab',
  'al-taawoun',
  'alaves',
  'atalanta',
  'bologna',
  'cagliari',
  'diriyah',
  'fiorentina',
  'frosinone',
  'genoa',
  'lazio',
  'lecce',
  'monza',
  'neom',
  'parma',
  'sassuolo',
  'torino',
  'udinese',
  'venezia',
  // منتخبات أوروبا وأندية الدوري الفرنسي المضافة
  'albania',
  'andorra',
  'armenia',
  'austria',
  'azerbaijan',
  'belarus',
  'belgium',
  'bosnia-herzegovina',
  'bulgaria',
  'croatia',
  'cyprus',
  'czech-republic',
  'denmark',
  'netherlands',
  'england',
  'estonia',
  'faroe-islands',
  'finland',
  'france',
  'georgia',
  'germany',
  'gibraltar',
  'greece',
  'hungary',
  'iceland',
  'israel',
  'italy',
  'kazakhstan',
  'kosovo',
  'latvia',
  'liechtenstein',
  'lithuania',
  'luxembourg',
  'malta',
  'moldova',
  'montenegro',
  'north-macedonia',
  'northern-ireland',
  'norway',
  'poland',
  'portugal',
  'ireland',
  'romania',
  'san-marino',
  'scotland',
  'serbia',
  'slovakia',
  'slovenia',
  'spain',
  'sweden',
  'switzerland',
  'turkey',
  'ukraine',
  'wales',
  'angers',
  'monaco',
  'auxerre',
  'brest',
  'le-havre',
  'le-mans',
  'lorient',
  'nice',
  'paris-fc',
  'strasbourg',
  'toulouse',
  'troyes',
  // منتخبات الخليج (كأس الخليج)
  'bahrain',
  'qatar',
  'yemen',
  'united-arab-emirates',
  'saudi-arabia',
  'oman',
  'iraq',
  'kuwait',
};
